/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package zdf.learn.com.commonUtils.data.avro.schema.can300;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Type3OutsideUseData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5860601484784814217L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Type3OutsideUseData\",\"namespace\":\"zdf.learn.com.commonUtils.data.avro.schema.can300\",\"fields\":[{\"name\":\"dateTime\",\"type\":\"string\"},{\"name\":\"label\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"},{\"name\":\"unit\",\"type\":\"string\"}],\"default\":null}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Type3OutsideUseData> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Type3OutsideUseData> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Type3OutsideUseData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Type3OutsideUseData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Type3OutsideUseData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Type3OutsideUseData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Type3OutsideUseData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Type3OutsideUseData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Type3OutsideUseData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence dateTime;
  private java.lang.CharSequence label;
  private java.lang.CharSequence value;
  private java.lang.CharSequence unit;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Type3OutsideUseData() {}

  /**
   * All-args constructor.
   * @param dateTime The new value for dateTime
   * @param label The new value for label
   * @param value The new value for value
   * @param unit The new value for unit
   */
  public Type3OutsideUseData(java.lang.CharSequence dateTime, java.lang.CharSequence label, java.lang.CharSequence value, java.lang.CharSequence unit) {
    this.dateTime = dateTime;
    this.label = label;
    this.value = value;
    this.unit = unit;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return dateTime;
    case 1: return label;
    case 2: return value;
    case 3: return unit;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: dateTime = (java.lang.CharSequence)value$; break;
    case 1: label = (java.lang.CharSequence)value$; break;
    case 2: value = (java.lang.CharSequence)value$; break;
    case 3: unit = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'dateTime' field.
   * @return The value of the 'dateTime' field.
   */
  public java.lang.CharSequence getDateTime() {
    return dateTime;
  }


  /**
   * Sets the value of the 'dateTime' field.
   * @param value the value to set.
   */
  public void setDateTime(java.lang.CharSequence value) {
    this.dateTime = value;
  }

  /**
   * Gets the value of the 'label' field.
   * @return The value of the 'label' field.
   */
  public java.lang.CharSequence getLabel() {
    return label;
  }


  /**
   * Sets the value of the 'label' field.
   * @param value the value to set.
   */
  public void setLabel(java.lang.CharSequence value) {
    this.label = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.lang.CharSequence getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.CharSequence value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'unit' field.
   * @return The value of the 'unit' field.
   */
  public java.lang.CharSequence getUnit() {
    return unit;
  }


  /**
   * Sets the value of the 'unit' field.
   * @param value the value to set.
   */
  public void setUnit(java.lang.CharSequence value) {
    this.unit = value;
  }

  /**
   * Creates a new Type3OutsideUseData RecordBuilder.
   * @return A new Type3OutsideUseData RecordBuilder
   */
  public static zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder newBuilder() {
    return new zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder();
  }

  /**
   * Creates a new Type3OutsideUseData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Type3OutsideUseData RecordBuilder
   */
  public static zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder newBuilder(zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder other) {
    if (other == null) {
      return new zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder();
    } else {
      return new zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder(other);
    }
  }

  /**
   * Creates a new Type3OutsideUseData RecordBuilder by copying an existing Type3OutsideUseData instance.
   * @param other The existing instance to copy.
   * @return A new Type3OutsideUseData RecordBuilder
   */
  public static zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder newBuilder(zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData other) {
    if (other == null) {
      return new zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder();
    } else {
      return new zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder(other);
    }
  }

  /**
   * RecordBuilder for Type3OutsideUseData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Type3OutsideUseData>
    implements org.apache.avro.data.RecordBuilder<Type3OutsideUseData> {

    private java.lang.CharSequence dateTime;
    private java.lang.CharSequence label;
    private java.lang.CharSequence value;
    private java.lang.CharSequence unit;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.dateTime)) {
        this.dateTime = data().deepCopy(fields()[0].schema(), other.dateTime);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.label)) {
        this.label = data().deepCopy(fields()[1].schema(), other.label);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.value)) {
        this.value = data().deepCopy(fields()[2].schema(), other.value);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.unit)) {
        this.unit = data().deepCopy(fields()[3].schema(), other.unit);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Type3OutsideUseData instance
     * @param other The existing instance to copy.
     */
    private Builder(zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.dateTime)) {
        this.dateTime = data().deepCopy(fields()[0].schema(), other.dateTime);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.label)) {
        this.label = data().deepCopy(fields()[1].schema(), other.label);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.value)) {
        this.value = data().deepCopy(fields()[2].schema(), other.value);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.unit)) {
        this.unit = data().deepCopy(fields()[3].schema(), other.unit);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'dateTime' field.
      * @return The value.
      */
    public java.lang.CharSequence getDateTime() {
      return dateTime;
    }


    /**
      * Sets the value of the 'dateTime' field.
      * @param value The value of 'dateTime'.
      * @return This builder.
      */
    public zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder setDateTime(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.dateTime = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'dateTime' field has been set.
      * @return True if the 'dateTime' field has been set, false otherwise.
      */
    public boolean hasDateTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'dateTime' field.
      * @return This builder.
      */
    public zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder clearDateTime() {
      dateTime = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'label' field.
      * @return The value.
      */
    public java.lang.CharSequence getLabel() {
      return label;
    }


    /**
      * Sets the value of the 'label' field.
      * @param value The value of 'label'.
      * @return This builder.
      */
    public zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder setLabel(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.label = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'label' field has been set.
      * @return True if the 'label' field has been set, false otherwise.
      */
    public boolean hasLabel() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'label' field.
      * @return This builder.
      */
    public zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder clearLabel() {
      label = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.CharSequence getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder setValue(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.value = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder clearValue() {
      value = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'unit' field.
      * @return The value.
      */
    public java.lang.CharSequence getUnit() {
      return unit;
    }


    /**
      * Sets the value of the 'unit' field.
      * @param value The value of 'unit'.
      * @return This builder.
      */
    public zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder setUnit(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.unit = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'unit' field has been set.
      * @return True if the 'unit' field has been set, false otherwise.
      */
    public boolean hasUnit() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'unit' field.
      * @return This builder.
      */
    public zdf.learn.com.commonUtils.data.avro.schema.can300.Type3OutsideUseData.Builder clearUnit() {
      unit = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Type3OutsideUseData build() {
      try {
        Type3OutsideUseData record = new Type3OutsideUseData();
        record.dateTime = fieldSetFlags()[0] ? this.dateTime : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.label = fieldSetFlags()[1] ? this.label : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.value = fieldSetFlags()[2] ? this.value : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.unit = fieldSetFlags()[3] ? this.unit : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Type3OutsideUseData>
    WRITER$ = (org.apache.avro.io.DatumWriter<Type3OutsideUseData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Type3OutsideUseData>
    READER$ = (org.apache.avro.io.DatumReader<Type3OutsideUseData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.dateTime);

    out.writeString(this.label);

    out.writeString(this.value);

    out.writeString(this.unit);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.dateTime = in.readString(this.dateTime instanceof Utf8 ? (Utf8)this.dateTime : null);

      this.label = in.readString(this.label instanceof Utf8 ? (Utf8)this.label : null);

      this.value = in.readString(this.value instanceof Utf8 ? (Utf8)this.value : null);

      this.unit = in.readString(this.unit instanceof Utf8 ? (Utf8)this.unit : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.dateTime = in.readString(this.dateTime instanceof Utf8 ? (Utf8)this.dateTime : null);
          break;

        case 1:
          this.label = in.readString(this.label instanceof Utf8 ? (Utf8)this.label : null);
          break;

        case 2:
          this.value = in.readString(this.value instanceof Utf8 ? (Utf8)this.value : null);
          break;

        case 3:
          this.unit = in.readString(this.unit instanceof Utf8 ? (Utf8)this.unit : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










