/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package cn.cbdc.canconvert.avro.schema.can300;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TimeAndCoordinate extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1727430985657522980L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TimeAndCoordinate\",\"namespace\":\"cn.cbdc.canconvert.avro.schema.can300\",\"fields\":[{\"name\":\"gps\",\"type\":{\"type\":\"record\",\"name\":\"GPS\",\"fields\":[{\"name\":\"gpsDate\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"point\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Point\",\"fields\":[{\"name\":\"latitude\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"longitude\",\"type\":[\"null\",\"double\"],\"default\":null}]}]},{\"name\":\"pdop\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"hdop\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"vdop\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"measureCount\",\"type\":[\"null\",\"long\"],\"default\":null}],\"default\":null}},{\"name\":\"mm\",\"type\":{\"type\":\"record\",\"name\":\"MM\",\"fields\":[{\"name\":\"point\",\"type\":[\"null\",\"Point\"],\"default\":null},{\"name\":\"rticLinkId\",\"type\":[\"null\",\"long\"],\"default\":null}],\"default\":null}}],\"default\":null}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TimeAndCoordinate> ENCODER =
      new BinaryMessageEncoder<TimeAndCoordinate>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TimeAndCoordinate> DECODER =
      new BinaryMessageDecoder<TimeAndCoordinate>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TimeAndCoordinate> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TimeAndCoordinate> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TimeAndCoordinate>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TimeAndCoordinate to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TimeAndCoordinate from a ByteBuffer. */
  public static TimeAndCoordinate fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public cn.cbdc.canconvert.avro.schema.can300.GPS gps;
  @Deprecated public cn.cbdc.canconvert.avro.schema.can300.MM mm;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TimeAndCoordinate() {}

  /**
   * All-args constructor.
   * @param gps The new value for gps
   * @param mm The new value for mm
   */
  public TimeAndCoordinate(cn.cbdc.canconvert.avro.schema.can300.GPS gps, cn.cbdc.canconvert.avro.schema.can300.MM mm) {
    this.gps = gps;
    this.mm = mm;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return gps;
    case 1: return mm;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: gps = (cn.cbdc.canconvert.avro.schema.can300.GPS)value$; break;
    case 1: mm = (cn.cbdc.canconvert.avro.schema.can300.MM)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'gps' field.
   * @return The value of the 'gps' field.
   */
  public cn.cbdc.canconvert.avro.schema.can300.GPS getGps() {
    return gps;
  }

  /**
   * Sets the value of the 'gps' field.
   * @param value the value to set.
   */
  public void setGps(cn.cbdc.canconvert.avro.schema.can300.GPS value) {
    this.gps = value;
  }

  /**
   * Gets the value of the 'mm' field.
   * @return The value of the 'mm' field.
   */
  public cn.cbdc.canconvert.avro.schema.can300.MM getMm() {
    return mm;
  }

  /**
   * Sets the value of the 'mm' field.
   * @param value the value to set.
   */
  public void setMm(cn.cbdc.canconvert.avro.schema.can300.MM value) {
    this.mm = value;
  }

  /**
   * Creates a new TimeAndCoordinate RecordBuilder.
   * @return A new TimeAndCoordinate RecordBuilder
   */
  public static cn.cbdc.canconvert.avro.schema.can300.TimeAndCoordinate.Builder newBuilder() {
    return new cn.cbdc.canconvert.avro.schema.can300.TimeAndCoordinate.Builder();
  }

  /**
   * Creates a new TimeAndCoordinate RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TimeAndCoordinate RecordBuilder
   */
  public static cn.cbdc.canconvert.avro.schema.can300.TimeAndCoordinate.Builder newBuilder(cn.cbdc.canconvert.avro.schema.can300.TimeAndCoordinate.Builder other) {
    return new cn.cbdc.canconvert.avro.schema.can300.TimeAndCoordinate.Builder(other);
  }

  /**
   * Creates a new TimeAndCoordinate RecordBuilder by copying an existing TimeAndCoordinate instance.
   * @param other The existing instance to copy.
   * @return A new TimeAndCoordinate RecordBuilder
   */
  public static cn.cbdc.canconvert.avro.schema.can300.TimeAndCoordinate.Builder newBuilder(cn.cbdc.canconvert.avro.schema.can300.TimeAndCoordinate other) {
    return new cn.cbdc.canconvert.avro.schema.can300.TimeAndCoordinate.Builder(other);
  }

  /**
   * RecordBuilder for TimeAndCoordinate instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TimeAndCoordinate>
    implements org.apache.avro.data.RecordBuilder<TimeAndCoordinate> {

    private cn.cbdc.canconvert.avro.schema.can300.GPS gps;
    private cn.cbdc.canconvert.avro.schema.can300.GPS.Builder gpsBuilder;
    private cn.cbdc.canconvert.avro.schema.can300.MM mm;
    private cn.cbdc.canconvert.avro.schema.can300.MM.Builder mmBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(cn.cbdc.canconvert.avro.schema.can300.TimeAndCoordinate.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.gps)) {
        this.gps = data().deepCopy(fields()[0].schema(), other.gps);
        fieldSetFlags()[0] = true;
      }
      if (other.hasGpsBuilder()) {
        this.gpsBuilder = cn.cbdc.canconvert.avro.schema.can300.GPS.newBuilder(other.getGpsBuilder());
      }
      if (isValidValue(fields()[1], other.mm)) {
        this.mm = data().deepCopy(fields()[1].schema(), other.mm);
        fieldSetFlags()[1] = true;
      }
      if (other.hasMmBuilder()) {
        this.mmBuilder = cn.cbdc.canconvert.avro.schema.can300.MM.newBuilder(other.getMmBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing TimeAndCoordinate instance
     * @param other The existing instance to copy.
     */
    private Builder(cn.cbdc.canconvert.avro.schema.can300.TimeAndCoordinate other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.gps)) {
        this.gps = data().deepCopy(fields()[0].schema(), other.gps);
        fieldSetFlags()[0] = true;
      }
      this.gpsBuilder = null;
      if (isValidValue(fields()[1], other.mm)) {
        this.mm = data().deepCopy(fields()[1].schema(), other.mm);
        fieldSetFlags()[1] = true;
      }
      this.mmBuilder = null;
    }

    /**
      * Gets the value of the 'gps' field.
      * @return The value.
      */
    public cn.cbdc.canconvert.avro.schema.can300.GPS getGps() {
      return gps;
    }

    /**
      * Sets the value of the 'gps' field.
      * @param value The value of 'gps'.
      * @return This builder.
      */
    public cn.cbdc.canconvert.avro.schema.can300.TimeAndCoordinate.Builder setGps(cn.cbdc.canconvert.avro.schema.can300.GPS value) {
      validate(fields()[0], value);
      this.gpsBuilder = null;
      this.gps = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'gps' field has been set.
      * @return True if the 'gps' field has been set, false otherwise.
      */
    public boolean hasGps() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'gps' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public cn.cbdc.canconvert.avro.schema.can300.GPS.Builder getGpsBuilder() {
      if (gpsBuilder == null) {
        if (hasGps()) {
          setGpsBuilder(cn.cbdc.canconvert.avro.schema.can300.GPS.newBuilder(gps));
        } else {
          setGpsBuilder(cn.cbdc.canconvert.avro.schema.can300.GPS.newBuilder());
        }
      }
      return gpsBuilder;
    }

    /**
     * Sets the Builder instance for the 'gps' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public cn.cbdc.canconvert.avro.schema.can300.TimeAndCoordinate.Builder setGpsBuilder(cn.cbdc.canconvert.avro.schema.can300.GPS.Builder value) {
      clearGps();
      gpsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'gps' field has an active Builder instance
     * @return True if the 'gps' field has an active Builder instance
     */
    public boolean hasGpsBuilder() {
      return gpsBuilder != null;
    }

    /**
      * Clears the value of the 'gps' field.
      * @return This builder.
      */
    public cn.cbdc.canconvert.avro.schema.can300.TimeAndCoordinate.Builder clearGps() {
      gps = null;
      gpsBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'mm' field.
      * @return The value.
      */
    public cn.cbdc.canconvert.avro.schema.can300.MM getMm() {
      return mm;
    }

    /**
      * Sets the value of the 'mm' field.
      * @param value The value of 'mm'.
      * @return This builder.
      */
    public cn.cbdc.canconvert.avro.schema.can300.TimeAndCoordinate.Builder setMm(cn.cbdc.canconvert.avro.schema.can300.MM value) {
      validate(fields()[1], value);
      this.mmBuilder = null;
      this.mm = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'mm' field has been set.
      * @return True if the 'mm' field has been set, false otherwise.
      */
    public boolean hasMm() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'mm' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public cn.cbdc.canconvert.avro.schema.can300.MM.Builder getMmBuilder() {
      if (mmBuilder == null) {
        if (hasMm()) {
          setMmBuilder(cn.cbdc.canconvert.avro.schema.can300.MM.newBuilder(mm));
        } else {
          setMmBuilder(cn.cbdc.canconvert.avro.schema.can300.MM.newBuilder());
        }
      }
      return mmBuilder;
    }

    /**
     * Sets the Builder instance for the 'mm' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public cn.cbdc.canconvert.avro.schema.can300.TimeAndCoordinate.Builder setMmBuilder(cn.cbdc.canconvert.avro.schema.can300.MM.Builder value) {
      clearMm();
      mmBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'mm' field has an active Builder instance
     * @return True if the 'mm' field has an active Builder instance
     */
    public boolean hasMmBuilder() {
      return mmBuilder != null;
    }

    /**
      * Clears the value of the 'mm' field.
      * @return This builder.
      */
    public cn.cbdc.canconvert.avro.schema.can300.TimeAndCoordinate.Builder clearMm() {
      mm = null;
      mmBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TimeAndCoordinate build() {
      try {
        TimeAndCoordinate record = new TimeAndCoordinate();
        if (gpsBuilder != null) {
          record.gps = this.gpsBuilder.build();
        } else {
          record.gps = fieldSetFlags()[0] ? this.gps : (cn.cbdc.canconvert.avro.schema.can300.GPS) defaultValue(fields()[0]);
        }
        if (mmBuilder != null) {
          record.mm = this.mmBuilder.build();
        } else {
          record.mm = fieldSetFlags()[1] ? this.mm : (cn.cbdc.canconvert.avro.schema.can300.MM) defaultValue(fields()[1]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TimeAndCoordinate>
    WRITER$ = (org.apache.avro.io.DatumWriter<TimeAndCoordinate>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TimeAndCoordinate>
    READER$ = (org.apache.avro.io.DatumReader<TimeAndCoordinate>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
