// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resource/demo.proto

package zdf.learn.com.commonUtils.data.protobuf;

public interface FileBeanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FileBean)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes file = 1;</code>
   * @return The file.
   */
  com.google.protobuf.ByteString getFile();

  /**
   * <code>string fileName = 2;</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <code>string fileName = 2;</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>int32 opt = 6;</code>
   * @return The opt.
   */
  int getOpt();

  /**
   * <code>bytes fileLength = 15;</code>
   * @return The fileLength.
   */
  com.google.protobuf.ByteString getFileLength();
}
