// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resource/demo.proto

package zdf.learn.com.commonUtils.data.protobuf;

/**
 * <pre>
 *第一个类名称为FileBean，乃是实体bean。
 * </pre>
 *
 * Protobuf type {@code FileBean}
 */
public final class FileBean extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FileBean)
    FileBeanOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FileBean.newBuilder() to construct.
  private FileBean(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileBean() {
    file_ = com.google.protobuf.ByteString.EMPTY;
    fileName_ = "";
    fileLength_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FileBean();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return zdf.learn.com.commonUtils.data.protobuf.Demo.internal_static_FileBean_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return zdf.learn.com.commonUtils.data.protobuf.Demo.internal_static_FileBean_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            zdf.learn.com.commonUtils.data.protobuf.FileBean.class, zdf.learn.com.commonUtils.data.protobuf.FileBean.Builder.class);
  }

  public static final int FILE_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString file_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes file = 1;</code>
   * @return The file.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getFile() {
    return file_;
  }

  public static final int FILENAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fileName_ = "";
  /**
   * <code>string fileName = 2;</code>
   * @return The fileName.
   */
  @java.lang.Override
  public java.lang.String getFileName() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileName_ = s;
      return s;
    }
  }
  /**
   * <code>string fileName = 2;</code>
   * @return The bytes for fileName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileNameBytes() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPT_FIELD_NUMBER = 6;
  private int opt_ = 0;
  /**
   * <code>int32 opt = 6;</code>
   * @return The opt.
   */
  @java.lang.Override
  public int getOpt() {
    return opt_;
  }

  public static final int FILELENGTH_FIELD_NUMBER = 15;
  private com.google.protobuf.ByteString fileLength_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes fileLength = 15;</code>
   * @return The fileLength.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getFileLength() {
    return fileLength_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!file_.isEmpty()) {
      output.writeBytes(1, file_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileName_);
    }
    if (opt_ != 0) {
      output.writeInt32(6, opt_);
    }
    if (!fileLength_.isEmpty()) {
      output.writeBytes(15, fileLength_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!file_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, file_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileName_);
    }
    if (opt_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, opt_);
    }
    if (!fileLength_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(15, fileLength_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof zdf.learn.com.commonUtils.data.protobuf.FileBean)) {
      return super.equals(obj);
    }
    zdf.learn.com.commonUtils.data.protobuf.FileBean other = (zdf.learn.com.commonUtils.data.protobuf.FileBean) obj;

    if (!getFile()
        .equals(other.getFile())) return false;
    if (!getFileName()
        .equals(other.getFileName())) return false;
    if (getOpt()
        != other.getOpt()) return false;
    if (!getFileLength()
        .equals(other.getFileLength())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILE_FIELD_NUMBER;
    hash = (53 * hash) + getFile().hashCode();
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFileName().hashCode();
    hash = (37 * hash) + OPT_FIELD_NUMBER;
    hash = (53 * hash) + getOpt();
    hash = (37 * hash) + FILELENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getFileLength().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static zdf.learn.com.commonUtils.data.protobuf.FileBean parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static zdf.learn.com.commonUtils.data.protobuf.FileBean parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static zdf.learn.com.commonUtils.data.protobuf.FileBean parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static zdf.learn.com.commonUtils.data.protobuf.FileBean parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static zdf.learn.com.commonUtils.data.protobuf.FileBean parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static zdf.learn.com.commonUtils.data.protobuf.FileBean parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static zdf.learn.com.commonUtils.data.protobuf.FileBean parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static zdf.learn.com.commonUtils.data.protobuf.FileBean parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static zdf.learn.com.commonUtils.data.protobuf.FileBean parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static zdf.learn.com.commonUtils.data.protobuf.FileBean parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static zdf.learn.com.commonUtils.data.protobuf.FileBean parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static zdf.learn.com.commonUtils.data.protobuf.FileBean parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(zdf.learn.com.commonUtils.data.protobuf.FileBean prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *第一个类名称为FileBean，乃是实体bean。
   * </pre>
   *
   * Protobuf type {@code FileBean}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FileBean)
      zdf.learn.com.commonUtils.data.protobuf.FileBeanOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zdf.learn.com.commonUtils.data.protobuf.Demo.internal_static_FileBean_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zdf.learn.com.commonUtils.data.protobuf.Demo.internal_static_FileBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zdf.learn.com.commonUtils.data.protobuf.FileBean.class, zdf.learn.com.commonUtils.data.protobuf.FileBean.Builder.class);
    }

    // Construct using zdf.learn.com.commonUtils.data.protobuf.FileBean.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      file_ = com.google.protobuf.ByteString.EMPTY;
      fileName_ = "";
      opt_ = 0;
      fileLength_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return zdf.learn.com.commonUtils.data.protobuf.Demo.internal_static_FileBean_descriptor;
    }

    @java.lang.Override
    public zdf.learn.com.commonUtils.data.protobuf.FileBean getDefaultInstanceForType() {
      return zdf.learn.com.commonUtils.data.protobuf.FileBean.getDefaultInstance();
    }

    @java.lang.Override
    public zdf.learn.com.commonUtils.data.protobuf.FileBean build() {
      zdf.learn.com.commonUtils.data.protobuf.FileBean result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public zdf.learn.com.commonUtils.data.protobuf.FileBean buildPartial() {
      zdf.learn.com.commonUtils.data.protobuf.FileBean result = new zdf.learn.com.commonUtils.data.protobuf.FileBean(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(zdf.learn.com.commonUtils.data.protobuf.FileBean result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.file_ = file_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.fileName_ = fileName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.opt_ = opt_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.fileLength_ = fileLength_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof zdf.learn.com.commonUtils.data.protobuf.FileBean) {
        return mergeFrom((zdf.learn.com.commonUtils.data.protobuf.FileBean)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(zdf.learn.com.commonUtils.data.protobuf.FileBean other) {
      if (other == zdf.learn.com.commonUtils.data.protobuf.FileBean.getDefaultInstance()) return this;
      if (other.getFile() != com.google.protobuf.ByteString.EMPTY) {
        setFile(other.getFile());
      }
      if (!other.getFileName().isEmpty()) {
        fileName_ = other.fileName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getOpt() != 0) {
        setOpt(other.getOpt());
      }
      if (other.getFileLength() != com.google.protobuf.ByteString.EMPTY) {
        setFileLength(other.getFileLength());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              file_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              fileName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 48: {
              opt_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 48
            case 122: {
              fileLength_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 122
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString file_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes file = 1;</code>
     * @return The file.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getFile() {
      return file_;
    }
    /**
     * <code>bytes file = 1;</code>
     * @param value The file to set.
     * @return This builder for chaining.
     */
    public Builder setFile(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      file_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bytes file = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFile() {
      bitField0_ = (bitField0_ & ~0x00000001);
      file_ = getDefaultInstance().getFile();
      onChanged();
      return this;
    }

    private java.lang.Object fileName_ = "";
    /**
     * <code>string fileName = 2;</code>
     * @return The fileName.
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fileName = 2;</code>
     * @return The bytes for fileName.
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fileName = 2;</code>
     * @param value The fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fileName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string fileName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileName() {
      fileName_ = getDefaultInstance().getFileName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string fileName = 2;</code>
     * @param value The bytes for fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fileName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int opt_ ;
    /**
     * <code>int32 opt = 6;</code>
     * @return The opt.
     */
    @java.lang.Override
    public int getOpt() {
      return opt_;
    }
    /**
     * <code>int32 opt = 6;</code>
     * @param value The opt to set.
     * @return This builder for chaining.
     */
    public Builder setOpt(int value) {

      opt_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 opt = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOpt() {
      bitField0_ = (bitField0_ & ~0x00000004);
      opt_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString fileLength_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes fileLength = 15;</code>
     * @return The fileLength.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getFileLength() {
      return fileLength_;
    }
    /**
     * <code>bytes fileLength = 15;</code>
     * @param value The fileLength to set.
     * @return This builder for chaining.
     */
    public Builder setFileLength(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      fileLength_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bytes fileLength = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileLength() {
      bitField0_ = (bitField0_ & ~0x00000008);
      fileLength_ = getDefaultInstance().getFileLength();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FileBean)
  }

  // @@protoc_insertion_point(class_scope:FileBean)
  private static final zdf.learn.com.commonUtils.data.protobuf.FileBean DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new zdf.learn.com.commonUtils.data.protobuf.FileBean();
  }

  public static zdf.learn.com.commonUtils.data.protobuf.FileBean getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileBean>
      PARSER = new com.google.protobuf.AbstractParser<FileBean>() {
    @java.lang.Override
    public FileBean parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FileBean> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileBean> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public zdf.learn.com.commonUtils.data.protobuf.FileBean getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

